# docker-compose.production.yml
version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: paymir121/foodgram-project-react-backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/

  frontend:
    image: paymir121/foodgram-project-react-frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: paymir121/foodgram-project-react-gateway
    env_file: .env
    ports:
      - 8088:80
    volumes:
      - static:/staticfiles/
      - media:/app/media/