@TOKEN = Token 27abd72acd2b1ff8a69363c6e98f8217837fe59e

###

POST http://127.0.0.1:8000/api/recipes/1/favorite/
Content-Type: application/json
Authorization: {{TOKEN}}

{
}

###
DELETE http://127.0.0.1:8000/api/recipes/1/favorite/
Content-Type: application/json
Authorization: {{TOKEN}}

{
}

###
get http://127.0.0.1:8000/api/recipes/?page=1&limit=6&is_favorited=1
Content-Type: application/json
Authorization: {{TOKEN}}

{
}