@TOKEN = Token 6c57c9e12e9d16bfd009fb5478e4f00748bcf2d3
@HTTP_ADDRES = http://127.0.0.1:8088
###
GET {{HTTP_ADDRES}}/api/users/subscriptions/
Content-Type: application/json
Authorization: {{TOKEN}}

{
}

###
POST {{HTTP_ADDRES}}/api/users/1/subscribe/
Content-Type: application/json
Authorization: {{TOKEN}}

{
}

###
delete {{HTTP_ADDRES}}/api/users/2/subscribe/
Content-Type: application/json
Authorization: {{TOKEN}}

{
}