

GET http://127.0.0.1:8000/api/users/subscriptions/
Content-Type: application/json
Authorization: Token 9fa29db2e36847390d1e7b3bc9e1ae51ef371c7b

{
}

###
POST http://127.0.0.1:8000/api/users/2/subscribe/
Content-Type: application/json
Authorization: Token 9fa29db2e36847390d1e7b3bc9e1ae51ef371c7b

{
}

###
delete http://127.0.0.1:8000/api/users/2/subscribe/
Content-Type: application/json
Authorization: Token 9fa29db2e36847390d1e7b3bc9e1ae51ef371c7b

{
}