@TOKEN = Token 91a68e4a1a0dfb548a2c7c1da8fd49b62072bb7b

###
GET http://127.0.0.1:8000/api/users/subscriptions/
Content-Type: application/json
Authorization: {{TOKEN}}

{
}

###
POST http://127.0.0.1:8000/api/users/1/subscribe/
Content-Type: application/json
Authorization: {{TOKEN}}

{
}

###
delete http://127.0.0.1:8000/api/users/2/subscribe/
Content-Type: application/json
Authorization: {{TOKEN}}

{
}