
GET http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: Token 9fa29db2e36847390d1e7b3bc9e1ae51ef371c7b

{
}

###
GET http://127.0.0.1:8000/api/recipes/2/
Content-Type: application/json
Authorization: Token 9fa29db2e36847390d1e7b3bc9e1ae51ef371c7b

{
}

###

Post http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: Token 9fa29db2e36847390d1e7b3bc9e1ae51ef371c7b

{
  "ingredients": [
    {
    "id": 1123,
    "amount": 10
    }
  ],
    "tags": [
    1
  ],
    "name": "recipy2",
    "image": null,
    "text": "recipy",
    "cooking_time": 3
}

###
PATCH http://127.0.0.1:8000/api/recipes/3/
Content-Type: application/json
Authorization: Token 9fa29db2e36847390d1e7b3bc9e1ae51ef371c7b

{
  "ingredients": [
    {
      "id": 2,
      "amount": 13
    }
  ],
  "tags": [
    1
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "recipy2",
  "text": "strdscsing",
  "cooking_time": 155
}
