
GET http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: Token 3b4fd0222100e0ce010de66ebc889bf6579e08f6

{
}

###
GET http://127.0.0.1:8000/api/recipes/2/
Content-Type: application/json
Authorization: Token 3b4fd0222100e0ce010de66ebc889bf6579e08f6

{
}

###

Post http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: Token 3b4fd0222100e0ce010de66ebc889bf6579e08f6

{
  "ingredients": [
    {
    "id": 1123,
    "amount": 10
    }
  ],
    "tags": [
    1
  ],
    "name": "recipy2",
    "image": null,
    "text": "recipywqd",
    "cooking_time": 3
}

###
PATCH http://127.0.0.1:8000/api/recipes/3/
Content-Type: application/json
Authorization: Token 3b4fd0222100e0ce010de66ebc889bf6579e08f6

{
  "ingredients": [
    {
      "id": 2,
      "amount": 13
    }
  ],
  "tags": [
    1
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "recipy2",
  "text": "strdscsing",
  "cooking_time": 155
}

###
get http://127.0.0.1:8000/api/recipes/?page=1&limit=6&tags=slug
Content-Type: application/json
Authorization: Token 27abd72acd2b1ff8a69363c6e98f8217837fe59e

{
}