@TOKEN = Token 91a68e4a1a0dfb548a2c7c1da8fd49b62072bb7b

###
GET http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: {{TOKEN}}

{
}

###
GET http://127.0.0.1:8000/api/recipes/1/
Content-Type: application/json
Authorization: {{TOKEN}}

{
}

###
Post http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: {{TOKEN}}

{
  "ingredients": [
    {
    "id": 1123,
    "amount": 10
    },
    {
    "id": 13,
    "amount": 10
    }
  ],
    "tags": [
    1
  ],
    "name": "recicpy2",
    "image": null,
    "text": "recipyvwqd",
    "cooking_time": 34
}

###
PATCH http://127.0.0.1:8000/api/recipes/3/
Content-Type: application/json
Authorization: {{TOKEN}}

{
  "ingredients": [
    {
      "id": 44,
      "amount": 13
    },
    {
    "id": 13,
    "amount": 10
    }
  ],
  "tags": [
    1
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "recipy2",
  "text": "strdscsing",
  "cooking_time": 155
}


###
GET http://127.0.0.1:8000/api/recipes/?page=1&limit=6&author=1
Content-Type: application/json
Authorization: {{TOKEN}}

{
}

###
GET http://127.0.0.1:8000/api/recipes/?page=1&limit=6&tags=slug
Content-Type: application/json
Authorization: {{TOKEN}}

{
}

###
get http://127.0.0.1:8000/api/recipes/?page=1&limit=6&is_favorited=1
Content-Type: application/json
Authorization: {{TOKEN}}

{
}

###
get http://127.0.0.1:8000/api/recipes/?page=1&limit=6&is_in_shopping_cart=1
Content-Type: application/json
Authorization: {{TOKEN}}

{
}