
POST http://127.0.0.1:8000/api/recipes/1/shopping_cart/
Content-Type: application/json
Authorization: Token f7a6cfd79ea9a12e0c470f479bf0c96bca150363

{
}

###
DELETE http://127.0.0.1:8000/api/recipes/1/shopping_cart/
Content-Type: application/json
Authorization: Token f7a6cfd79ea9a12e0c470f479bf0c96bca150363

{
}

###
get http://127.0.0.1:8000/api/recipes/download_shopping_cart/
Authorization: Token f7a6cfd79ea9a12e0c470f479bf0c96bca150363

{
}