@TOKEN = Token 91a68e4a1a0dfb548a2c7c1da8fd49b62072bb7b
@HTTP_ADDRES = http://127.0.0.1:8088
###
POST {{HTTP_ADDRES}}/api/recipes/1/shopping_cart/
Content-Type: application/json
Authorization: {{TOKEN}}

{
}

###
DELETE {{HTTP_ADDRES}}/api/recipes/1/shopping_cart/
Content-Type: application/json
Authorization: {{TOKEN}}

{
}

###
get {{HTTP_ADDRES}}/api/recipes/download_shopping_cart/
Authorization: {{TOKEN}}

{
}