###

POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
    "email": "nikox12@mail.ru",
    "username": "nikjox",
    "password": "456852Zx",
    "first_name": "kewk",
    "last_name": "wsq"
}

###

POST http://127.0.0.1:8000/api/auth/token/
Content-Type: application/json

{
    "email": "nikox12@mail.ru",
    "username": "nikjox",
    "password": "456852Zx",
    "first_name": "kewk",
    "last_name": "wsq"
}

###

GET http://127.0.0.1:8000/api/users/1/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjkyMzU5NDE5LCJpYXQiOjE2ODk3Njc0MTksImp0aSI6ImMxYzJlMjczZTFmZTQzMmY4OWNiNzEwOTJkNWZkYTMwIiwidXNlcl9pZCI6Mn0.odaLlP5au-qWBPzj-MK4S0rosVTHsgDrY5p7Im-QqTU

{
    "email": "nikox12@mail.ru",
    "username": "nikjox",
    "password": "456852Zx",
    "first_name": "kewk",
    "last_name": "wsq"
}

