@TOKEN = Token 91a68e4a1a0dfb548a2c7c1da8fd49b62072bb7b

###
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
    "email": "nik3ox1e21@mail.ru",
    "username": "nikox1323@mail.ru",
    "password": "456852Zx",
    "first_name": "kewk",
    "last_name": "wsq"
}

###
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
    "email": "nik3ox1e21@mail.ru",
    "password": "456852Zx"
}

###
POST http://127.0.0.1:8000/api/users/set_password/
Content-Type: application/json
Authorization: {{TOKEN}}

{
"new_password": "456852Zxы",
"current_password": "456852Zx1ы"
}

###
GET http://127.0.0.1:8000/api/users/me/ 
Content-Type: application/json
Authorization: {{TOKEN}}

{
}


###
GET http://127.0.0.1:8000/api/users/1/ 
Content-Type: application/json
Authorization: {{TOKEN}}

{
}


