###
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
    "email": "nikox121212121@mail.ru",
    "username": "nikox1312121111",
    "password": "456852Zx",
    "first_name": "kewk",
    "last_name": "wsq"
}

###
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
    "email": "nikox121212121@mail.ru",
    "password": "456852Zx"
}


###
GET http://127.0.0.1:8000/api/users/me/ 
Content-Type: application/json
Authorization: Token 9fa29db2e36847390d1e7b3bc9e1ae51ef371c7b

{
    # "email": "nikox1222222@mail.ru",
    "username": "nikjox",
    "password": "456852Zx",
    "first_name": "kewk",
    "last_name": "wsq"
}

