# Generated by Django 3.2 on 2023-07-04 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(help_text='Введите название ингридиента', max_length=256, verbose_name='Ингредиенты')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('units', models.TextField(verbose_name='Единицы измерения')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название рецепта', max_length=256, verbose_name='Рецепт')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Картинка')),
                ('text', models.TextField(verbose_name='Текст')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('time_cooking', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(help_text='Введите название тега', max_length=256, verbose_name='Тег')),
                ('HEX_code', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecipyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipy.recipy')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipy.tag')),
            ],
        ),
        migrations.CreateModel(
            name='RecipyIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipy.ingredients')),
                ('recipy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipy.recipy')),
            ],
        ),
        migrations.AddField(
            model_name='recipy',
            name='ingredients',
            field=models.ManyToManyField(through='recipy.RecipyIngredients', to='recipy.Ingredients'),
        ),
        migrations.AddField(
            model_name='recipy',
            name='tag',
            field=models.ManyToManyField(through='recipy.RecipyTag', to='recipy.Tag'),
        ),
    ]
