# Generated by Django 3.2 on 2023-07-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='units',
            new_name='measurement_unit',
        ),
        migrations.RenameField(
            model_name='recipy',
            old_name='time_cooking',
            new_name='cooking_time',
        ),
        migrations.RenameField(
            model_name='recipy',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='HEX_code',
            new_name='color',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='count',
        ),
    ]
