# Generated by Django 3.2 on 2023-08-02 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipy', '0007_auto_20230730_1143'),
        ('recipy', '0008_auto_20230731_1452'),
    ]

    operations = [
    ]
