# Generated by Django 3.2 on 2023-08-14 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipy', '0010_auto_20230814_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
