# Generated by Django 3.2 on 2023-08-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipy', '0012_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
