# Generated by Django 3.2 on 2023-08-18 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipy', '0013_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipy',
            name='cooking_time',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='recipyingredient',
            name='amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1)]),
        ),
    ]
