# Generated by Django 3.2 on 2023-08-18 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipy", "0014_auto_20230818_1545"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipyingredient",
            name="ingredients",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients_in_recipy",
                to="recipy.ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="recipyingredient",
            name="recipy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipy_with_ingredients",
                to="recipy.recipy",
            ),
        ),
    ]
