# Generated by Django 3.2 on 2023-08-02 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230727_1749'),
        ('users', '0008_alter_user_email'),
    ]

    operations = [
    ]
